system:
  timeout: 30
  max_concurrent_crawlers: 10
  result_mode:
    real_time: true
    batch_interval: 5
  logging:
    level: "INFO"
    file: "logs/app.log"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    max_size: 10485760  # 10MB
    backup_count: 5

# 系统控制配置
control:
  pid_file: "data_aggregator.pid"
  auto_start_plugins: true
  startup_timeout: 30
  shutdown_timeout: 10

# 爬虫请求频率限制配置
crawler_rate_limits:
  # 全局频率限制配置
  default:
    requests_per_minute: 10    # 每分钟最多20次请求
    burst_size: 4             # 允许短时突发5次请求
    min_interval: 3           # 两次请求之间至少间隔3秒
  
  # 是否强制使用保守频率
  enforce_conservative_rate: yes  # 当为yes时，插件配置的频率不能超过默认频率

environment:
  shared_deps:
    feedparser:
      version: "6.0.10"
      shared: true
    aiohttp:
      version: "3.8.1"
      shared: true
    beautifulsoup4:
      version: "4.9.3"
      shared: true

plugins:
  timeout_per_plugin: 10
  retry_count: 3
  error_handling:
    log_level: "INFO"
    fail_strategy: "continue"

# 插件管理配置
management:
  auto_discovery: true
  auto_start: true  # 设置为 false 可以禁用自动启动
  health_check_interval: 60
  restart_on_failure: true
  max_restart_attempts: 3

development:
  debug: false
  auto_reload: true
  plugin_hot_reload: false

# Web界面配置
frontend:
  title: "Data Aggregator"
  theme: "light"
  language: "zh_CN"
  refresh_interval: 5000 